---

- name: add backports repo
  apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_lsb['codename'] }}-backports main restricted universe multiverse"
    state: present
    update_cache: yes

- name: install utilities from apt
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ apt_packages }}"

- name: set timezone
  copy:
    content: "{{ timezone }}"
    dest: /etc/timezone
    owner: root
    group:  root
    mode: 0644
  notify: update timezone

- name: create locale
  locale_gen:
    name: "{{ locale }}"
    state: present

- name: set locale
  command: "/usr/sbin/update-locale LANG={{ locale }}"

- name: ensure that ntpd is running and enabled
  service:
    name: ntp
    state: running
    enabled: yes

- name: run iptables command to load conntrack module
  command: "iptables -t nat -L"

- name: set number of open file descriptors system wide via PAM
  template:
    dest: "/etc/security/limits.d/fs_limits.conf"
    src: fs_limits.conf.j2
    mode: 0644
    owner: root
    group: root

- name: set sysctl values
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_dict:
    fs.file-max: "{{ os_max_open_files }}"
    fs.nr_open: "{{ os_max_open_files }}"
    net.nf_conntrack_max: "{{ nf_conntrack_max }}"
    net.core.somaxconn: "{{ net_core_somaxconn }}"
    net.ipv4.tcp_fin_timeout: "{{ tcp_fin_timeout }}"
    net.ipv4.tcp_window_scaling: "{{ tcp_window_scaling }}"
    net.ipv4.tcp_max_syn_backlog: "{{ tcp_max_syn_backlog }}"

- name: update sshd_config
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^MaxStartups"
    line: "MaxStartups 100"
    state: present

- name: update dhclient
  copy:
    src: dhclient.conf
    dest: /etc/dhcp/dhclient.conf
  when: ansible_lsb["codename"] == "trusty"

- name: upgrade kernel
  apt:
    update_cache: yes
    name: linux-generic-lts-vivid
    state: present
  when: ansible_kernel | version_compare("3.18.0", "lt")
  register: upgrade_kernel
