---

- name: bootstrap host
  hosts: vagrant
  tasks:
    - name: copy bootstrap script
      copy:
        src: "scripts/bootstrap.sh"
        dest: /tmp/bootstrap.sh
        mode: 0755
      tags: ["bootstrap"]
    - name: run bootstrap script
      shell: "UBUNTU_VERSION={{ lookup('env', 'UBUNTU_VERSION') }} /tmp/bootstrap.sh {{ ansible_lsb['codename'] }}" 
      tags: ["bootstrap"]

- name: install host (all)
  hosts: all
  roles:
    - role: baseline
      tags: ["baseline"]
    - role: kamaln7.swapfile
      swapfile_size: 1GB
      swapfile_swappiness: 60
      swapfile_location: /swapfile
      tags: ["swapfile"]
    - role: codedeploy
      tags: ["aws", "codedeploy"]
    - role: postgresql-client
      tags: ["postgresql-client"]
  vars:
    aws_region: us-east-1

- name: install host (trusty)
  hosts: trusty
  roles:
    - role: openresty
      tags: ["openresty"]
    - role: python
      tags: ["python"]
    - role: nodejs
      tags: ["nodejs"]
  vars:
    aws_region: us-east-1

- name: install host (xenial)
  hosts: xenial
  roles:
    - role: ecs-agent
      tags: ["ecs"]
  vars:
    aws_region: us-east-1
