---

- name: bootstrap host
  hosts: vagrant
  tasks:
    - name: run bootstrap script
      script: scripts/bootstrap.sh
      tags: ["bootstrap"]

- name: install host (all)
  hosts: all
  roles:
    - role: baseline
      tags: ["baseline"]
    - role: intel-networking
      tags: ["intel"]
    - role: kamaln7.swapfile
      swapfile_size: 1GB
      swapfile_swappiness: 60
      swapfile_location: /swapfile
      tags: ["swapfile"]
    - role: datadog-agent
      tags: ["datadog"]
    - role: postgresql-client
      tags: ["postgresql-client"]
    # Docker enabled ECS instances
    - role: docker-host
      tags: ["docker-host"]
    # ECS instances
    - role: ecs-agent
      tags: ["ecs"]
    # Legacy Web machines
    - role: codedeploy
      tags: ["codedeploy", "legacy"]
    - role: openresty
      tags: ["openresty", "legacy"]
    - role: python
      tags: ["python", "legacy"]
    - role: nodejs
      tags: ["nodejs", "legacy"]

  vars:
    aws_region: us-east-1
