---

- name: install python dependencies from apt
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - libffi-dev
    - libpq-dev
    - libpq5
    - libssl-dev
    - python-dev

- name: install python dependencies from pip
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpie
    - ndg-httpsclient
    - psycopg2
    - supervisor
    - virtualenv
    - virtualenvwrapper

- name: make sure supervisord directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/supervisor/conf.d
    - /var/log/supervisor

- name: install default supervisord configuration file
  copy:
    src: supervisord.conf
    dest: /etc/supervisord.conf

- name: install supervisord systemd script
  copy:
    src: supervisord.service
    dest: /etc/systemd/system/supervisord.service
    mode: 0644

- name: make sure supervisord is running and starts on boot
  service:
    name: supervisord
    state: started
    enabled: yes
