---

# Ansible role that closely translates to https://github.com/aws/amazon-ecs-agent into 

- name: Install requisite packages
  apt:
    name: python-docker
    state: present
    update_cache: yes

- name: Set up the directory the agent uses
  file: path={{ item }} state=directory
  with_items:
    - "{{ ecs_paths }}"

- name: Render template and deploy ECS agent config file
  template: src=ecs.config.j2 dest=/etc/ecs/ecs.config

- name: Set sysctl value for localhost route
  sysctl:
    name: net.ipv4.conf.all.route_localnet
    value: 1
    state: present

- iptables: table=nat chain=PREROUTING protocol=tcp destination=169.254.170.2 destination_port=80 jump=DNAT to_destination=127.0.0.1:51679 comment="Docker redirect traffic for AWS ECS agent - set by Ansible"
  become: yes
- iptables: table=nat chain=OUTPUT destination=169.254.170.2 protocol=tcp match=tcp destination_port=80 jump=REDIRECT to_ports=51679 comment="Docker redirect traffic for AWS ECS agent - set by Ansible"
  become: yes

- name: Manage AWS ECS agent Docker image
  docker:
    detach: true
    env:
      ECS_LOGFILE: /log/ecs-agent.log
      ECS_DATADIR: /data/
      ECS_ENABLE_TASK_IAM_ROLE: true
      ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST: true
    env_file: /etc/ecs/ecs.config
    image: amazon/amazon-ecs-agent:latest
    name: ecs-agent
    net: host
    pull: always
    restart_policy: on-failure
    restart_policy_retry: 10
    state: reloaded
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/ecs:/log
      - /var/lib/ecs/data:/data
