---

# Ansible role that closely translates to https://github.com/aws/amazon-ecs-agent into 

- name: Install prerequisite packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ packages }}"

- name: Set up the directory the agent uses
  file: path={{ item }} state=directory
  with_items:
    - "{{ ecs_paths }}"

- name: Customize ECS configuration
  template: src=ecs.config.j2 dest=/etc/ecs/ecs.config

- name: Enable the use of 127/8 for local routing purposes
  sysctl:
    name: net.ipv4.conf.all.route_localnet
    value: 1
    state: present

- name: Iptables PREROUTING rule for Docker redirect to allow traffic to AWS ECS container agent ports
  iptables: table=nat chain=PREROUTING protocol=tcp destination=169.254.170.2 destination_port=80 jump=DNAT to_destination=127.0.0.1:51679 comment="Docker redirect traffic for AWS ECS agent - set by Ansible"
  become: yes

- name: Iptables OUTPUT rule for Docker redirect to allow traffic to AWS ECS container agent ports
  iptables: table=nat chain=OUTPUT destination=169.254.170.2 protocol=tcp match=tcp destination_port=80 jump=REDIRECT to_ports=51679 comment="Docker redirect traffic for AWS ECS agent - set by Ansible"
  become: yes

- name: Add Docker PPA apt key
  apt_key:
    url: https://yum.dockerproject.org/gpg
    id: 2C52609D

- name: Add Docker PPA
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo/ ubuntu-{{ ansible_lsb['codename'] }} main"
    state: present

- name: Install Docker Engine
  apt:
    name: docker-engine
    state: present
    update_cache: yes

- name: Pull AWS ECS agent image and set config
  docker_container:
    env:
      ECS_LOGFILE: /log/ecs-agent.log
      ECS_DATADIR: /data/
      ECS_ENABLE_TASK_IAM_ROLE: true
      ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST: true
    env_file: /etc/ecs/ecs.config
    image: amazon/amazon-ecs-agent:latest
    name: ecs-agent
    network_mode: host
    pull: true
    restart_policy: on-failure
    restart_retries: 10
    state: started
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/ecs:/log
      - /var/lib/ecs/data:/data
