---

locale: en_US.UTF-8
timezone: "America/Los_Angeles"
apt_packages: []

### Sysctl values
# FS file limits
os_max_open_files: 1000000
# Netfilter Connection Tracking
nf_conntrack_max: 1048576
# The maximum number of "backlogged sockets".  Default is 128.
net_core_somaxconn: 511
# TCP tuning
tcp_fin_timeout: 15
tcp_window_scaling: 1
tcp_max_syn_backlog: 3240000
