---

locale: en_US.UTF-8
timezone: "America/Los_Angeles"
apt_packages: []

sysctl_config:
# FS file limits
  fs.file-max: 1000000
  fs.nr_open: 1000000
# Netfilter Connection Tracking
  net.nf_conntrack_max: 1048576
# The maximum number of "backlogged sockets".  Default is 128.
  net.core.somaxconn: 511
# TCP tuning
  net.ipv4.tcp_fin_timeout: 15
  net.ipv4.tcp_window_scaling: 1
  net.ipv4.tcp_max_syn_backlog: 3240000

pip_packages:
  - psycopg2
  - httplib2
  - awscli
  - aws-shell

prereq_paths:
  - /opt/globality
