---

# Ansible role that closely translates to https://github.com/aws/amazon-ecs-agent into 

- name: Set up the directory the agent uses
  file: path={{ item }} state=directory
  with_items:
    - "{{ ecs_paths }}"

- name: Deploy ECS Agent container systemd config
  template:
    src: ecs-agent.service.j2
    dest: /etc/systemd/system/ecs-agent.service

- name: Deploy persistent iptables rules
  template:
    src: iptables.v4.j2
    dest: /etc/iptables/rules.v4

- name: Customize ECS configuration
  template:
    src: ecs.config.j2
    dest: /etc/ecs/ecs.config

- name: Deploy ECS Agent timer systemd config
  template:
    src: ecs-agent.timer.j2
    dest: /etc/systemd/system/ecs-agent.timer

- name: Load ECS Agent systemd timer
  systemd:
    name: ecs-agent.timer
    daemon_reload: yes
    enabled: yes
    state: started

- name: Load ECS Agent systemd config
  systemd:
    name: ecs-agent.service
    daemon_reload: yes
    enabled: no
    state: stopped
