---

- name: install python dependencies from apt
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - libffi-dev
    - libpq-dev
    - libpq5
    - libssl-dev
    - python-dev

- name: install python dependencies from pip
  pip: name={{ item }} state=present
  with_items:
    - supervisor
    - virtualenv
    - virtualenvwrapper

- name: make sure supervisord directories exist
  file: path={{ item }} state=directory
  with_items:
    - /etc/supervisor/conf.d
    - /var/log/supervisor

- name: install default supervisord configuration file
  copy: src=supervisord.conf dest=/etc/supervisord.conf

- name: install supervisord init script
  copy: src=supervisor.ubuntu.init-script dest=/etc/init.d/supervisor mode=u+rwx

- name: make sure supervisord is running and starts on boot
  service: name=supervisor state=started enabled=yes
