---

- name: add nginx apt repository
  apt_repository: repo='ppa:nginx/stable'

- name: install nginx
  apt: pkg=nginx state=latest

- name: push nginx configuration
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: create hostname path
  file: path=/usr/share/nginx/www/hostname state=directory owner=root

- name: update hostname.txt
  copy:
    content={{ inventory_hostname }}
    dest=/usr/share/nginx/www/hostname/hostname.txt
    owner=root
    group=root
    mode=644
  notify:
    - restart nginx

- name: remove default vhost
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - restart nginx
