---

- name: bootstrap host
  hosts: vagrant
  tasks:
    - name: copy bootstrap script
      copy:
        src: "{{ playbook_dir }}/../scripts/bootstrap.sh"
        dest: /tmp
        mode: 0755
      tags: ["bootstrap"]
    - name: run bootstrap script
      command: /tmp/bootstrap.sh
      tags: ["bootstrap"]

- name: install host
  hosts: all
  roles:
    - role: baseline
      tags: ["baseline"]
    - role: kamaln7.swapfile
      swapfile_size: 1GB
      swapfile_swappiness: 60
      swapfile_location: /swapfile
      tags: ["swapfile"]
    - role: codedeploy
      tags: ["aws", "codedeploy"]
    - role: cloudwatch
      tags: ["aws", "cloudwatch"]
    # - role: nginx
    #   tags: ["nginx"]
    - role: openresty
      tags: ["openresty"]
    - role: python
      tags: ["python"]
    - role: nodejs
      tags: ["nodejs"]
  vars:
    aws_region: us-east-1
