---

- name: Pin version of PostgreSQL client
  copy:
    dest: /etc/apt/preferences.d/fixed-postgresql-client
    content: |
      Package: postgresql-client
      Pin: release v={{ postgresql_client_version }}
      Pin-Priority: 10

- name: Install apt key for PostgreSQL PPA
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Configure PostgreSQL PPA
  apt_repository:
    repo: "deb https://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main"
    update_cache: yes
    state: present

- name: Install PostgreSQL client
  apt:
    name: postgresql-client-{{ postgresql_client_version }}
    state: latest

- name: Get RDS SSL certificate
  get_url:
    url: https://s3.amazonaws.com/rds-downloads/rds-ca-2015-root.pem
    dest: /usr/local/share/ca-certificates/rds-ca-2015-root.crt
  register: rds_ca_bundle_downloaded

- name: Update CA certificates
  command: "update-ca-certificates"
  when: rds_ca_bundle_downloaded | changed
