---

- name: Pin version of PostgreSQL client
  copy:
    dest: /etc/apt/preferences.d/fixed-postgresql-client
    content: |
      Package: postgresql-client
      Pin: release v={{ postgresql_client_version }}
      Pin-Priority: 10

- name: Install apt key for PostgreSQL PPA
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Configure PostgreSQL PPA
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main"
    update_cache: yes
    state: present

- name: Install PostgreSQL client
  apt:
    name: postgresql-client-{{ postgresql_client_version }}
    state: latest
